### ISSUE TITLE
example raw data and Roi

### ISSUE THREAD

**Issue by hilge** [mbertalan/iPsychCNV#4]
Hi Marcelo.

I have tried to play around with your package today, but do not have any raw data on my laptop.
Would it be possible to add in an short example raw data file (maybe scrambled somewhat so as to not give out anyone's genotype on github) that way i could have a go using the caller function.

Also can i ask what you mean by Roi. Should this maybe be defined in your readme.

Best,
Johan

**Comment by mbertalan** [comment]
Hej Johan! That is great. Download the package again. There is a small read
me in the website github. I created 2 functions to make a mock data. You
can simulate blood and pku. I will send you some slides that I created as
examples.
Roi has a default value. There are many objects being loaded when you call
iPsychCNV. Two can be used as Roi. The first is your list of region of
interest, roi. The second is an extended version, roiext.
I will send the slides in a separate email.
Cheers, Marcelo
