### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by hilge** [mbertalan/iPsychCNV#6]
This is not so much an issue with the package in it self, but issues encountered while installing the dependent packages that might be useful for other users to know about (Maybe under install on the homepage).

1) Installation of devtools fails - this may be solved by installing the OS package libcurl - multiple threads can be found on this issue. http://stackoverflow.com/questions/26445815/error-when-installing-devtools-package-for-r-in-ubuntu

2) a number of dependent R-packages fail as the installer cannot find -lquadmath. This issue may be resolved by installing r-base-dev. See http://stackoverflow.com/questions/6302209/building-r-package-getting-error-ld-cannot-find-lgfortran.

**Comment by mbertalan** [comment]
Thanks ! Already update the website with the information.
